---
- hosts: front
  become: true
  become_user: root
  become_method: sudo
  
  tasks:
  
  - name: Install NGINX
    ansible.builtin.dnf:
      name: nginx

  - name: Start Service
    ansible.builtin.systemd:
      name: "{{ main_service }}"
      state: started

  